amoreresto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls', namespace='restaurant')),
    path('', include('reservations.urls', namespace='reservations')),
]

reservations/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'reservations'

urlpatterns = [
    path('book_table/', views.book_table, name='book_table'),
    path('booking_success/', views.booking_success, name='booking_success'),  
    path('register/', views.register, name='register'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('view_bookings/', views.view_bookings, name='view_bookings'),
    path('reservations/<int:booking_id>/delete/', views.delete_booking, name='delete_booking'),
    path('custom_logout/', views.custom_logout, name='custom_logout'),
]

restaurant/urls.py
from django.urls import path
from . import views


app_name = 'restaurant'

urlpatterns = [
    path('', views.home, name='home'),
    path('food/', views.foodmenu, name='food'),
    path('drink/', views.beveragemenu, name='drink'),
    path('contact/', views.contact, name='contact'),
]

reservations/models.py
from django.db import models
from django.contrib.auth.models import User

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_time = models.DateTimeField()
    num_people = models.IntegerField()

    def __str__(self):
        return f'{self.user.username} - {self.date_time}'

restaurant/models.py
from django.db import models


class HomePage(models.Model):
    """ 
    Model for the introduction section on landing page 
    """
    introduction = models.TextField()

    class Meta:
        verbose_name_plural = 'Home Page'

    def __str__(self):
        return "Content for Landing Page"


class Category(models.Model):
    """
    Model for menu items categories 
    """
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class MenuItems(models.Model):
    """
    Model for the menu items
    """
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category,related_name='menu_items', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Menu Items'

    def __str__(self):
        return self.name


class BeverageCategory(models.Model):
    """
    Model for drink categories in menu
    """
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Beverage Categories'

    def __str__(self):
        return self.name


class BeverageItems(models.Model):
    """
    Model for beverage items
    """
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    beverage_category = models.ForeignKey(BeverageCategory,related_name='beverage_items', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Beverage Items'

    def __str__(self):
        return self.name

reservations/forms.py
from django import forms
from django.contrib.auth.models import User


class BookingForm(forms.Form):
    date_time = forms.DateTimeField(label='Date and Time', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    num_people = forms.IntegerField(label='Number of People')


#class RegistrationForm(forms.ModelForm):
   # password = forms.CharField(label='Password', widget=forms.PasswordInput)

    #class Meta:
      #  model = User
       # fields = ['username', 'email']

reservations/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import BookingForm
from .models import Booking
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
#from .forms import RegistrationForm


@login_required
def book_table(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            date_time = form.cleaned_data['date_time']
            num_people = form.cleaned_data['num_people']
            booking = Booking.objects.create(user=request.user, date_time=date_time, num_people=num_people)
            return redirect('reservations:booking_success')
    else:
        form = BookingForm()
    return render(request, 'reservations/book_table.html', {'form': form})


def booking_success(request):
    #return render(request, 'reservations/booking_success.html')

    latest_booking = Booking.objects.latest('id')  # Retrieve the latest booking
    return render(request, 'reservations/booking_success.html', {'latest_booking': latest_booking})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # Authenticate the user after registration
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirect the user to the table booking page after successful registration
                return redirect('reservations:book_table')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def view_bookings(request):
    user_bookings = Booking.objects.filter(user=request.user)
    return render(request, 'view_bookings.html', {'user_bookings': user_bookings})


def delete_booking(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id, user=request.user)
    
    if request.method == 'POST':
        booking.delete()
        return redirect('reservations:view_bookings')

    return render(request, 'reservations/confirm_delete_booking.html', {'booking': booking})


def custom_logout(request):
    return render(request, 'custom_logout.html')

restaurant/views.py
from django.shortcuts import render
from .models import HomePage, Category, MenuItems, BeverageCategory, BeverageItems


def home(request):
    """
    View to display introduction text on landing page
    """
    content_home = HomePage.objects.last()

    context = {'content_home': content_home}

    return render(request, 'index.html', context)


def foodmenu(request):
    """
    View to show all food menu items 
    """
    categories = Category.objects.all()
    menu_items = MenuItems.objects.all()
    
    context = {'categories': categories, 'menu_items': menu_items}

    return render(request, 'food.html', context)


def beveragemenu(request):
    """
    View to show all beverages available 
    """
    beverage_categories = BeverageCategory.objects.all()
    beverage_items = BeverageItems.objects.all()
    
    context = {'beverage_categories': beverage_categories, 'beverage_items': beverage_items}

    return render(request, 'drink.html', context)


def contact(request):
    """
    View to contact page
    """
    return render(request, 'contact.html')

reservations/templates/custom_logout.html
{% extends "base.html" %}
{% block title %}CIAO AMORE{% endblock %}

{% block content %}
    <h1>You have been logged out</h1>

{% endblock %}

reservations/templates/reservations/book_table.html
{% extends "base.html" %}
{% block title %}Booking Successful{% endblock %}

{% block content %}

    <h2>Book Table</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Book</button>
    </form>

{% endblock %}

reservations/templates/reservations/booking_success.html
{% extends "base.html" %}
{% block title %}Booking Successful{% endblock %}

{% block content %}

    <h2>Booking Successful</h2>
    <p>Your table has been booked successfully!</p>
    {% if latest_booking %}
        <p>Date and Time of Reservation: {{ latest_booking.date_time }}</p>
    {% endif %}

{% endblock %}

reservations/templates/reservations/confirm_delete_booking.html
{% extends "base.html" %}
{% block title %}Booking Deleted{% endblock %}

{% block content %}

    <h1>Confirm Delete Booking</h1>
    <p>Are you sure you want to delete the booking with the following details?</p>
    <p>Date and Time of Reservation: {{ booking.date_time }}</p>
    <form action="{% url 'reservations:delete_booking' booking.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Yes, Delete</button>
        <a href="{% url 'reservations:view_bookings' %}">Cancel</a>
    </form>

{% endblock %}

reservations/templates/view_bookings.html
{% extends "base.html" %}
{% block title %}Bookings{% endblock %}

{% block content %}

    <h1>Your Bookings</h1>
    <ul>
        {% for booking in user_bookings %}
            <li>
                Date and Time of Reservation: {{ booking.date_time }}
                <!-- Delete Button -->
                <form action="{% url 'reservations:delete_booking' booking.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            </li>
        {% empty %}
            <li>No bookings found.</li>
        {% endfor %}
    </ul>

{% endblock %}

restaurant/templates/contact.html
{% extends "base.html" %}
{% block title %}CONTACT{% endblock %}

{% block content %}

    <header>
        <h1>Contact Us</h1>
    </header>

    <main>
    
        <section>
            <h2>Contact Information</h2>
            <p>Restaurant Name: <a href="https://www.google.com/maps?q=Restaurant+Name">Ristorante AMORE</a></p>
            <p>Address: <a href="https://www.google.com/maps?q=123+Main+Street+City+State+ZIP">123 Main Street, City, State ZIP</a></p>
            <p>Phone: <a href="tel:+11234567890">123-456-7890</a></p>
            <p>Email: <a href="mailto:info@restaurant.com">info@restaurant.com</a></p>
        </section>


{% endblock %}

restaurant/templates/drink.html
{% extends "base.html" %}
{% block title %}Food Menu{% endblock %}

<!-- Beverage menu items listed in categories -->
{% block content %}
    <ul>
        {% for category in beverage_categories %}
            <h1>{{ category.name }}</h1>
            <ul>
                {% for item in category.beverage_items.all %}
                    <li>{{ item.name }} - €{{ item.price }}</li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>

{% endblock %}

restaurant/templates/food.html
{% extends "base.html" %}
{% block title %}Food Menu{% endblock %}

<!-- Food menu items listed in categories -->
{% block content %}
    <ul>
        {% for category in categories %}
            <h1>{{ category.name }}</h1>
            <ul>
                {% for item in category.menu_items.all %}
                    <li>{{ item.name }} - €{{ item.price }}</li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>

{% endblock %}

restaurant/templates/home/home.html
{% extends "base.html" %}
{% block title %}Welcome Home Amore{% endblock %}

<!-- About section for landing page -->
{% block content %}
    <div class="about container text-center">
        <h1>CIAO AMORE</h1>
        <p>{{ content_home.introduction }}</p>
    </div>
{% endblock %}


    

restaurant/templates/index.html
{% extends "base.html" %}
{% block title %}Welcome Home Amore{% endblock %}

<!-- About section for landing page -->
{% block content %}
    <div class="about container text-center">
        <h1>CIAO AMORE</h1>
        <p>{{ content_home.introduction }}</p>
    </div>
{% endblock %}


    

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Amore Italian Restaurant Site">
    <meta name="keywords" content="restaurant, italian, pasta, drinks, pizza">

    <title>{% block title %}{% endblock %}</title>
    
    <!-- Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Red+Hat+Display&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/a1bd9d75a9.js" crossorigin="anonymous"></script>
 
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Global CSS -->
    <link rel="stylesheet", href="{% static 'css/style.css' %}">

    <!-- Bootstrap JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'restaurant:home' %}">Ristorante AMORE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:food' %}">EAT</a></li>
            <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:drink' %}">DRINK</a></li>
            <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'reservations:view_bookings' %}">BOOKINGS</a></li>
            <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'reservations:logout' %}">LOGOUT</a></li>
            <li class="nav-item bg-light-subtle rounded"><a class="nav-link active btn" aria-current="page" href="{% url 'reservations:book_table' %}">BOOK A TABLE</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:food' %}">EAT</a></li>
            <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:drink' %}">DRINK</a></li>
            <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'restaurant:contact' %}">CONTACT</a></li>
            <li class="nav-item bg-light-subtle rounded"><a class="nav-link active btn" aria-current="page" href="{% url 'reservations:book_table' %}">BOOK A TABLE</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- About section on landign page-->
  {% block content %} 
  {% endblock %}

  <!-- Footer -->
  <footer>
    <div class=".container text-center">
      <div class="footer fixed-bottom">
        <!-- Social Media Icons-->
        <div class="footer-icon d-flex justify-content-center">
          <a href="https://facebook.com" target="_blank" rel="noopener" aria-label="Visit our Facebook page (opens in a new tab)"><i class="fa-brands fa-facebook" style="color: #050505;"></i></a>
          <a href="https://instagram.com" target="_blank" rel="noopener" aria-label="Visit our Instagram page (opens in a new tab)"><i class="fa-brands fa-instagram" style="color: #050505;"></i></a>
        </div>
        <!-- Copyright -->
        <div id="copyright">
          <p>&copy; 2024 M.K with amore</p>
        </div>
      </div>
    </div>
  </footer>
      
</body>

</html>